//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab9_database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Household
    {
        public int Id { get; set; }
        public int Id_animal { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Name_household { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
