//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab9_database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_tickets
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public Nullable<System.DateTime> Date_birth { get; set; }
        public Nullable<System.DateTime> Date_order_ticket { get; set; }
        public Nullable<System.DateTime> Date_visiting { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Count { get; set; }
        public string Household { get; set; }
        public string Animal { get; set; }
    }
}
